In [1]:
import numpy as np
list = [1, 2, 3, 4]
npList = np.array(list)
list = list * 2
npList = npList * 2
print(list)
print(npList)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [2]:
a = np.zeros((5,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#2 dimensional array using tuple
a = np.zeros((5,4))
print(a.ndim)

2


In [49]:
# 1 dimensional array
b = np.ones(3)
print(b)

[1. 1. 1.]


In [4]:
c = np.empty(3)
print(c)

[0. 0. 0.]


In [5]:
d = np.arange(5)
print(d)

[0 1 2 3 4]


In [6]:
e = np.zeros([1,2,3,4])
print(e)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [7]:
e.ndim

4

In [8]:
e.dtype

dtype('float64')

In [10]:
e.shape

(1, 2, 3, 4)

In [9]:
a = np.zeros((5,4), dtype = np.int32)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
a.dtype

dtype('int32')

In [13]:
x = np.zeros(list)
print(x)

[[[[[[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]]




   [[[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]

      [[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0.]]]]



    [[[[0. 0. 0. 0.]
       [0. 0. 0. 0.]
       [0. 0. 0. 0

In [25]:
import numpy as np
text = "due to the import of Karachi with the help of it, it is to beatifull to libve oin it"
sp =text.split(" ")
a = np.array(sp)
print(a)

['due' 'to' 'the' 'import' 'of' 'Karachi' 'with' 'the' 'help' 'of' 'it,'
 'it' 'is' 'to' 'beatifull' 'to' 'libve' 'oin' 'it']
