In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([2])
arr3 = arr * arr2
print(arr3)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
arr3 = arr * arr2
print(arr3)

[[ 1  4  9]
 [ 4 10 18]]


In [25]:
text = "One of the key features of NumPy is its N-dimensional array object"

sp =text.split(" ")
a = np.array(sp)
print(a)

['One' 'of' 'the' 'key' 'features' 'of' 'NumPy' 'is' 'its' 'N-dimensional'
 'array' 'object']


In [11]:
txt = "Hamza,how dare you! You can't do that! Mr. Asshad focus"
txt += "Do you want break?, or if you don't want we can practice"

In [12]:
print(txt)

Hamza,how dare you! You can't do that! Mr. Asshad focusDo you want break?, or if you don't want we can practice


In [16]:
list1 = []
sp = txt.split(" ")
for i in  range(len(sp)):
    element_ln = len(sp[i])
    if (element_ln < 5):
        list1.append(sp[i])
    
num_arr = np.array(list1)
print(num_arr)

['dare' 'you!' 'You' 'do' 'Mr.' 'you' 'want' 'or' 'if' 'you' 'want' 'we'
 'can']


In [27]:
txt2 = "Here are some of the things you will find inn Numpy"
arr4 = np.array(txt2.split(" "))
lnth = np.vectorize(len)
print(arr4[lnth(arr4) < 5])


['Here' 'are' 'some' 'of' 'the' 'you' 'will' 'find' 'inn']


array([4, 3, 4, 2, 3, 6, 3, 4, 4, 3, 5])

In [41]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [46]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 151 ms


In [47]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Wall time: 3.85 s


In [14]:
a = np.arange(50)

In [21]:
a.shape

(50,)

In [31]:
b = np.full(50,a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [36]:
#eye or identitiy
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
p = np.arange(50)