In [1]:
import numpy as np

In [2]:
ndarray = np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(ndarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [3]:
print("ndim",ndarray.ndim,"shape",ndarray.shape)

ndim 2 shape (4, 3)


In [4]:
#use of colon is optional means select all
print(ndarray[2,2])
print(ndarray[2])

33
[31 32 33]


In [5]:
ndarray = np.array([
    [[111,112,113,114],[121,122,123,124],[131,132,133,134]],
    [[211,212,213,214],[221,222,223,224],[231,232,233,234]],
    [[311,312,313,314],[321,322,323,324],[331,332,333,334]],
    [[411,412,413,414],[421,422,423,424],[431,432,433,434]],
                   ])
print(ndarray)

[[[111 112 113 114]
  [121 122 123 124]
  [131 132 133 134]]

 [[211 212 213 214]
  [221 222 223 224]
  [231 232 233 234]]

 [[311 312 313 314]
  [321 322 323 324]
  [331 332 333 334]]

 [[411 412 413 414]
  [421 422 423 424]
  [431 432 433 434]]]


In [6]:
print("ndim",ndarray.ndim,"shape",ndarray.shape)

ndim 3 shape (4, 3, 4)


In [7]:
print(ndarray[2:4,2,:1])

[[331]
 [431]]


In [8]:
import matplotlib.pylab as plt

In [9]:
imgarr = plt.imread("4k.jpg")

FileNotFoundError: [Errno 2] No such file or directory: '4k.jpg'

In [14]:
print(imgarr)

[[[22 32 33]
  [25 33 35]
  [25 33 35]
  ...
  [25 35 37]
  [24 34 36]
  [23 33 35]]

 [[22 32 33]
  [26 34 36]
  [27 35 37]
  ...
  [24 34 36]
  [25 35 37]
  [25 35 37]]

 [[28 38 39]
  [28 36 38]
  [25 33 35]
  ...
  [24 34 36]
  [26 36 38]
  [26 36 38]]

 ...

 [[24 28 29]
  [24 28 29]
  [24 28 29]
  ...
  [24 28 29]
  [24 28 29]
  [24 28 29]]

 [[24 28 29]
  [24 28 29]
  [24 28 29]
  ...
  [24 28 29]
  [24 28 29]
  [24 28 29]]

 [[24 28 29]
  [24 28 29]
  [24 28 29]
  ...
  [24 28 29]
  [24 28 29]
  [24 28 29]]]


In [17]:
print("Shape: ",imgarr.shape ,"\n" ,"Dimension: ",imgarr.ndim)

Shape:  (3456, 5184, 3) 
 Dimension:  3


In [45]:
imgarr[3455]

array([[24, 28, 29],
       [24, 28, 29],
       [24, 28, 29],
       ...,
       [24, 28, 29],
       [24, 28, 29],
       [24, 28, 29]], dtype=uint8)

In [1]:
import pandas as s

In [2]:
samosa = s.Series([12,33,13,76,45,0,31],index = ["mon","tue","wed","thurs","fri","sat","sun"])

In [3]:
print(samosa)

mon      12
tue      33
wed      13
thurs    76
fri      45
sat       0
sun      31
dtype: int64


In [4]:
print(samosa[samosa > 20])

tue      33
thurs    76
fri      45
sun      31
dtype: int64


In [6]:
print(samosa)

mon      12
tue      33
wed      13
thurs    76
fri      45
sat       0
sun      31
dtype: int64
