In [1]:
import numpy as np

In [7]:
my_arr = np.arange(1000000)

In [115]:
%time for i in range(10):my_arr = my_arr * 2

Wall time: 40 ms


In [116]:
my_list = list(range(1000000))
i = 0
%time for z in range(10):list2 = [x * 2 for x in my_list]

Wall time: 1.48 s


In [243]:
intr = np.random.randn(10)
intr

array([-0.49169469, -0.09675249, -0.21593358,  1.2959974 , -0.10580031,
        0.39436971,  0.60184977, -0.3353928 ,  2.77526607, -0.16266507])

In [236]:
c = np.random.standard_normal((5,5))
print(c)

[[ 1.27738603 -0.67600481 -0.31790342 -1.22301381 -1.24937954]
 [ 0.90260716  1.26856545  1.04096923  0.2740662  -0.50977546]
 [-0.60051314 -0.60215998  1.0868407   1.24031586 -1.29776501]
 [-0.83219584 -0.12384228 -0.00522366  1.24744373 -0.46460006]
 [ 0.22084186 -0.3156829   0.10369951 -0.93650356  0.24482573]]


In [194]:
for y in intr:
    if y > 1:
        print(y)

1.3208673986792188


In [204]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [206]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [229]:
emp = np.empty(10,dtype = int)

In [223]:
emp

array([-163093472,        545,  -75440376,        545,  -75440312,
              545,  -75440248,        545,  -75440184,        545])

In [220]:
ful = np.full(10, fill_value = 7)

In [221]:
ful

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [259]:
one_like = np.ones_like(10)
one_like

array(1)

In [258]:
one_only = np.ones(10)
one_only

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [261]:
zeros_like = np.zeros_like(10)
zeros_like

array(0)

In [297]:
#Generate Random Number between 10 and 299
random_nu = np.random.randint(10,299)

In [298]:
random_nu

51

In [345]:
new1 = np.random.randn(25)
new2 = new1.astype(int)
new3 = new2.astype(float)

In [349]:
print(new1)
print("\nand\n",new2)
print("\n\nand\n\n",new3)

[ 0.77118769  0.2109412   0.74002911  0.09951336  0.80338406  1.08486706
 -1.22239183 -1.99505422 -1.83358493 -0.52147869  0.63605208 -0.1959
  0.68127753 -0.29548985 -0.75333762 -0.51951231  0.31549865 -0.07479329
 -0.42555792  0.34629045  1.00753354 -0.77027424 -0.08276653 -1.10315801
 -0.38595415]

and
 [ 0  0  0  0  0  1 -1 -1 -1  0  0  0  0  0  0  0  0  0  0  0  1  0  0 -1
  0]


and

 [ 0.  0.  0.  0.  0.  1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  0. -1.  0.]


In [423]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [424]:
arr1[5:8] = 12

In [425]:
arr2 = arr1[5:8]

In [427]:
arr2[:] = 1234

In [429]:
print(arr2)

print(arr1)

[1234 1234 1234]
[   0    1    2    3    4 1234 1234 1234    8    9]
